#!/bin/bash

METADATA="package/metadata.desktop"
APPNAME=$(grep "X-KDE-PluginInfo-Name" $METADATA | sed 's/.*=//')

if [[ $1 == --install ]]; then
    plasmapkg2 --install package
else
    plasmapkg2 --upgrade package
fi

echo
echo '------------------------------------------------'
echo

plasmoidviewer -a $APPNAME
